#:kivy 2.0.0
<HomeScreen>:
    BoxLayout: 
        orientation:'vertical'
        Button:
            text:
                "TextScreen"
            on_release:
                app.change_screen("text_screen")
                root.manager.transition.direction = 'left'
        
        Button:
            text:
                "TextView Spans"
            on_release:
                app.change_screen("textViewspans_screen")
                root.manager.transition.direction = 'left'
