#:kivy 2.0.0
# Classe AppBar usada em todas as janelas
<AppBar@BoxLayout>:
    canvas:
        Color:
            rgba: 1, .6, .4, 1
        Rectangle:
            size: self.size
            pos: self.pos
    size_hint_y: None
    height: '56dp'
    #pos_hint_y: 'top'
    #orientation: 'horizontal'
    pos_hint: {'top':1}
    size_hint: (1, None)    
    padding: '16dp','8dp',0,'8dp'

<Icon@Button>:
    size_hint_x: None
    width: self.height
    border: 0,0,0,0

    