#:kivy 2.0.0
#:include kv/style.kv
<TextViewSpansScreen>:
    orientation: 'vertical'
    AppBar: 
        Label:
            text: "Titulo"      
        Icon:
            background_normal: 'icons/arrow-left-bold.png'
            on_release:
                app.change_screen("home_screen")
                root.manager.transition.direction = 'right'
        Icon:
            background_normal: 'icons/hammer-wrench.png'
   
    
